// Documentation page — describes exactly what the app does today, each section
// illustrated with real screenshots captured from the running app
// (public/screenshots/, generated by scripts/capture-screenshots.mjs).
import type { ReactNode } from "react";
import { assetUrl } from "../lib/assetUrl";

function Shot({ name, alt }: { name: string; alt: string }) {
  return (
    <figure className="my-6">
      <img
        src={assetUrl(`screenshots/${name}.png`)}
        alt={alt}
        loading="lazy"
        className="w-full rounded-lg border border-gray-200 shadow-sm"
      />
      <figcaption className="mt-1.5 text-xs text-gray-400">{alt}</figcaption>
    </figure>
  );
}

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: ReactNode;
}) {
  return (
    <section id={id} className="scroll-mt-20">
      <h2 className="text-xl font-bold text-gray-900 mt-10 mb-3">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-gray-700">{children}</div>
    </section>
  );
}

function Code({ children }: { children: ReactNode }) {
  return (
    <code className="px-1.5 py-0.5 rounded bg-gray-100 border border-gray-200 font-mono text-[12px] text-gray-800">
      {children}
    </code>
  );
}

function Kbd({ children }: { children: ReactNode }) {
  return (
    <kbd className="px-1.5 py-0.5 rounded border border-gray-300 border-b-2 bg-gray-50 font-mono text-[11px] text-gray-700">
      {children}
    </kbd>
  );
}

const TOC = [
  ["getting-started", "Getting started"],
  ["browsing-tables", "Browsing tables"],
  ["sql-editor", "SQL editor"],
  ["ai-completions", "AI completions"],
  ["structure-tab", "Structure tab"],
  ["record-drawer", "Record drawer"],
  ["performance", "Large files & performance"],
  ["agent-tools", "Agent tools (WebMCP)"],
  ["keyboard", "Keyboard shortcuts"],
] as const;

export function DocsPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-10">
      <h1 className="text-3xl font-bold text-gray-900">Documentation</h1>
      <p className="mt-2 text-gray-600">
        Everything this app can do today — no aspirational features. Every screenshot below is
        captured from the real app with the bundled demo database.
      </p>

      <nav className="mt-6 p-4 rounded-lg bg-gray-50 border border-gray-200">
        <ul className="grid grid-cols-2 sm:grid-cols-3 gap-x-4 gap-y-1.5 text-sm">
          {TOC.map(([id, label]) => (
            <li key={id}>
              <a href={`#/docs?${id}`} className="text-blue-600 hover:underline">
                {label}
              </a>
            </li>
          ))}
        </ul>
      </nav>

      <Section id="getting-started" title="Getting started">
        <p>
          Open the app and either <strong>drag a SQLite file anywhere onto the window</strong> or
          click the drop zone to browse for one (<Code>.sqlite</Code>, <Code>.db</Code>,{" "}
          <Code>.sqlite3</Code>, <Code>.db3</Code>). The file is validated by reading its 16-byte
          header before anything else happens — non-SQLite files are rejected immediately with a
          clear message.
        </p>
        <p>
          No file handy? The <strong>Load demo database</strong> button opens a bundled sample
          database with <Code>customers</Code>, <Code>orders</Code> and <Code>products</Code>{" "}
          tables.
        </p>
        <p>
          To start over with a different file, click <strong>Load another file</strong> in the
          header.
        </p>
        <Shot name="01-landing" alt="Landing page — drop a file anywhere or load the demo database" />
        <Shot name="02-database-open" alt="Database opened — tables listed in the left sidebar with row counts" />
      </Section>

      <Section id="browsing-tables" title="Browsing tables">
        <p>
          The left sidebar lists every table in the database with its row count. Clicking a table
          opens a <strong>Data tab</strong> that runs{" "}
          <Code>SELECT * FROM "table" LIMIT 100</Code> by default.
        </p>
        <p>
          Each table row in the sidebar also has a hover shortcut (the 🏗️ icon) that opens the
          table's <a href="#/docs?structure-tab" className="text-blue-600 hover:underline">Structure</a>{" "}
          tab directly.
        </p>
        <Shot name="03-data-tab" alt="Data tab — Monaco editor on top, virtualized data grid below" />
      </Section>

      <Section id="sql-editor" title="SQL editor">
        <p>
          Every Data tab has a full SQL editor at the top. It starts pre-filled with the default
          table query; edit it freely and press <strong>Run</strong> (or{" "}
          <Kbd>Ctrl</Kbd>+<Kbd>Enter</Kbd>) to execute against the open database. The grid below
          shows the result.
        </p>
        <Shot name="04-custom-query" alt="Custom SQL — an aggregated GROUP BY query and its result grid" />
        <p>
          <strong>Formatting.</strong> The <strong>Format</strong> button (or{" "}
          <Kbd>Shift</Kbd>+<Kbd>Alt</Kbd>+<Kbd>F</Kbd>) rewrites your SQL with consistent
          uppercase keywords and indentation via sql-formatter's SQLite dialect. Formatting runs
          through the editor's normal edit stack, so <Kbd>Ctrl</Kbd>+<Kbd>Z</Kbd> undoes it. SQL
          that cannot be parsed shows a format error instead of touching the editor.
        </p>
        <p>
          <strong>Schema-aware autocomplete.</strong> While typing, the editor suggests table
          names from the open database (ranked above generic SQL keywords); after a{" "}
          <Code>table.</Code> it suggests that table's columns with their types. The schema
          catalog is built in the background when a database opens — one <Code>PRAGMA
          table_info</Code> per table.
        </p>
        <Shot name="05-autocomplete" alt="Autocomplete — table suggestions while typing, columns after a dot" />
        <p>
          Multiple tabs can be open at once (Data tabs for different tables or queries, plus
          Structure tabs); the tab bar auto-scrolls to keep the active tab visible.
        </p>
        <Shot name="08-tabs" alt="Multiple tabs open — data tabs and structure tabs side by side" />
      </Section>

      <Section id="ai-completions" title="AI completions (local, optional)">
        <p>
          The editor also offers Copilot-style <strong>ghost-text completions</strong> powered by
          Qwen2.5-Coder-1.5B running entirely in your browser via WebLLM — no server, no API key,
          and the model weights are downloaded from this site, not Hugging Face.
        </p>
        <p>
          The AI preloads in the background as soon as the app opens; a small status pill in the
          header shows progress (<Code>loading …%</Code>) until the model is ready. Suggestions
          appear as gray ghost text and are accepted with <Kbd>Tab</Kbd>. The prompt includes your
          database's schema, so completions reference real tables and columns.
        </p>
        <p>
          <strong>Nothing depends on it.</strong> If your browser has no WebGPU, the model fails
          to load, or you close the tab mid-download, the app behaves exactly the same — the pill
          simply disappears and autocomplete falls back to the schema-aware suggestions above.
          The model (~845 MB) is fetched once and cached by the browser; the fetch script is{" "}
          <Code>bun run model:fetch</Code>.
        </p>
      </Section>

      <Section id="structure-tab" title="Structure tab">
        <p>
          Open a table's structure from the sidebar's hover icon (🏗️) to see two grids:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            <strong>Columns</strong> — name, declared type, <Code>NOT NULL</Code> flag, default
            value and primary-key flag (straight from <Code>PRAGMA table_info</Code>).
          </li>
          <li>
            <strong>Indexes</strong> — index name, uniqueness, origin (auto-created for PK/UNIQUE
            vs. explicit) and the indexed columns (from <Code>PRAGMA index_list</Code> +{" "}
            <Code>PRAGMA index_info</Code>).
          </li>
        </ul>
        <Shot name="06-structure" alt="Structure tab — columns grid and indexes grid" />
      </Section>

      <Section id="record-drawer" title="Record drawer">
        <p>
          <strong>Double-click any row</strong> in a data grid to open that record in a
          right-side drawer as a form: each column gets a read-only field matching its type —
          number inputs for numeric columns, date/datetime inputs for date columns, a textarea
          for long text. The primary key is badged <Code>PK</Code>. Close it with the × button,
          clicking the backdrop, or <Kbd>Esc</Kbd>.
        </p>
        <p>
          Rows are matched by their actual <Code>rowid</Code> — this works correctly even for
          tables with TEXT primary keys or <Code>WITHOUT ROWID</Code> tables, where the first
          visible column is not the rowid.
        </p>
        <Shot name="07-record-drawer" alt="Record drawer — one record shown as a typed, read-only form" />
      </Section>

      <Section id="performance" title="Large files & performance">
        <ul className="list-disc pl-5 space-y-1">
          <li>
            <strong>Multi-gigabyte databases</strong> open instantly: the file is handed to the
            SQLite worker as a blob reference and pages are read from disk on demand — the whole
            file is never loaded into memory.
          </li>
          <li>
            <strong>Virtualized grid</strong> — only visible rows are rendered; scrolling renders
            more on the fly. The page layout stays fixed: only the data grid and the sidebar
            scroll.
          </li>
          <li>
            <strong>WAL-mode databases</strong> open like any other file: the explorer presents
            them as read-only snapshots of the last checkpointed state (a single dropped file
            cannot provide the <Code>-wal</Code>/<Code>-shm</Code> side files).
          </li>
          <li>
            <strong>Read-only everywhere</strong> — the database opens in immutable mode; queries
            cannot modify your file.
          </li>
        </ul>
      </Section>

      <Section id="agent-tools" title="Agent tools (WebMCP)">
        <p>
          The app registers three read-only tools on <Code>document.modelContext</Code> (via the
          WebMCP polyfill), so AI agents with the MCP-B extension (or Chrome's native support, as
          it lands) can explore the database alongside you. Every tool also{" "}
          <strong>reflects its action in the UI</strong>, and SQL errors are returned verbatim
          from SQLite.
        </p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="text-left text-xs uppercase tracking-wider text-gray-500 border-b border-gray-200">
                <th className="py-2 pr-4">Tool</th>
                <th className="py-2 pr-4">Input</th>
                <th className="py-2">Behavior</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 align-top">
              <tr>
                <td className="py-2 pr-4 font-mono text-[12px]">list_tables</td>
                <td className="py-2 pr-4">search?</td>
                <td className="py-2">Markdown table of tables + row counts; the sidebar list filters to match.</td>
              </tr>
              <tr>
                <td className="py-2 pr-4 font-mono text-[12px]">view_table</td>
                <td className="py-2 pr-4">table</td>
                <td className="py-2">
                  Columns, indexes and related tables (foreign keys in both directions); opens the
                  table's Structure tab.
                </td>
              </tr>
              <tr>
                <td className="py-2 pr-4 font-mono text-[12px]">select_table</td>
                <td className="py-2 pr-4">sql, page?</td>
                <td className="py-2">
                  Runs SQL with a hard limit of 1000 records per page; returns a markdown table
                  plus total records, total pages and current page; opens the result as a tab.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </Section>

      <Section id="keyboard" title="Keyboard shortcuts">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <tbody className="divide-y divide-gray-100">
              <tr>
                <td className="py-2 pr-6 whitespace-nowrap">
                  <Kbd>Ctrl</Kbd>+<Kbd>Enter</Kbd> / <Kbd>⌘</Kbd>+<Kbd>Enter</Kbd>
                </td>
                <td className="py-2">Run the query in the editor</td>
              </tr>
              <tr>
                <td className="py-2 pr-6 whitespace-nowrap">
                  <Kbd>Shift</Kbd>+<Kbd>Alt</Kbd>+<Kbd>F</Kbd>
                </td>
                <td className="py-2">Format SQL</td>
              </tr>
              <tr>
                <td className="py-2 pr-6 whitespace-nowrap">
                  <Kbd>Ctrl</Kbd>+<Kbd>Space</Kbd> / <Kbd>⌃</Kbd>+<Kbd>Space</Kbd>
                </td>
                <td className="py-2">Trigger autocomplete</td>
              </tr>
              <tr>
                <td className="py-2 pr-6 whitespace-nowrap">
                  <Kbd>Esc</Kbd>
                </td>
                <td className="py-2">Close the record drawer or dismiss autocomplete</td>
              </tr>
            </tbody>
          </table>
        </div>
      </Section>
    </div>
  );
}
